/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SBadge: typeof import('@soybeanjs/ui')['SBadge']
    SDialog: typeof import('@soybeanjs/ui')['SDialog']
    SInput: typeof import('@soybeanjs/ui')['SInput']
  }
}
